import type { BossDef } from './types';

export const BOSSES: Record<string, BossDef> = {
  coldPyreWarden: {
    id: 'coldPyreWarden',
    name: 'Eskel',
    title: 'Warden of the Cold Pyre',
    zone: 'approach',
    secret: false,
    hpMult: 1.0,
    dmgMult: 1.0,
    poiseMult: 1.0,
    soulMult: 1.0,
    soulWeapon: 'wardenCleaver',
    soulSpell: 'pyreBloom',
    drops: { estusShard: 1, shard: 4 },
    shape: 'warden',
    phases: [
      {
        name: 'The Watch',
        at: 1.0,
        attackInterval: 4.0,
        attacks: [
          { id: 'cleave', name: 'Cleave', windup: 1.2, mult: 1.2, weight: 3 },
          { id: 'overhead', name: 'Warden\'s Overhead', windup: 1.9, mult: 2.2, weight: 1 },
        ],
        text: 'The Warden rises from the ash of his own pyre.',
      },
      {
        name: 'Backdraft',
        at: 0.6,
        attackInterval: 3.4,
        attacks: [
          { id: 'cleave', name: 'Cleave', windup: 1.0, mult: 1.3, weight: 3 },
          { id: 'sweep', name: 'Pyre Sweep', windup: 1.4, mult: 1.7, weight: 2 },
        ],
        resist: { fire: 0.3 },
        mechanic: 'backdraft',
        mechParam: 7,
        text: 'The cleaver ignites. Every strike feeds it. Strike too fast and the flame answers in kind.',
      },
      {
        name: 'Cold Pyre',
        at: 0.3,
        attackInterval: 3.0,
        attacks: [
          { id: 'cleave', name: 'Cleave', windup: 0.9, mult: 1.4, weight: 3 },
          { id: 'overhead', name: 'Warden\'s Overhead', windup: 1.6, mult: 2.6, weight: 2 },
        ],
        mechanic: 'staggerOnly',
        mechParam: 0.15,
        text: 'The flame gutters. He plants his feet and will not be moved. Break his stance, or barely scratch him.',
      },
    ],
    lore: 'Eskel kept the Pyre for a hundred years after the last pilgrim. When it went cold he did not leave his post, because no one told him to. He is not angry with you. He is simply still on duty.',
  },
  hangedPilgrim: {
    id: 'hangedPilgrim',
    name: 'The Hanged Pilgrim',
    title: 'Who Would Not Stay Hanged',
    zone: 'approach',
    secret: true,
    hpMult: 1.0,
    dmgMult: 1.2,
    poiseMult: 1.3,
    soulMult: 1.0,
    soulWeapon: 'gallowsRope',
    soulSpell: 'lastRites',
    drops: { soulVessel: 1, largeShard: 3 },
    shape: 'hanged',
    secretCondition: { kind: 'kills', zone: 'approach', count: 40 },
    phases: [
      {
        name: 'Swaying',
        at: 1.0,
        attackInterval: 3.2,
        attacks: [
          { id: 'swing', name: 'Swing', windup: 1.1, mult: 1.3, weight: 3 },
          { id: 'drop', name: 'Drop', windup: 1.7, mult: 2.0, weight: 1 },
        ],
        mechanic: 'regen',
        mechParam: 0.02,
        text: 'The rope creaks. Where it frays, the flesh knits back. Only wounds that keep bleeding will stay open.',
      },
      {
        name: 'Cut Down',
        at: 0.5,
        attackInterval: 2.6,
        attacks: [
          { id: 'claw', name: 'Claw', windup: 0.8, mult: 1.1, weight: 3 },
          { id: 'strangle', name: 'Strangle', windup: 1.5, mult: 2.3, weight: 1 },
        ],
        mechanic: 'regen',
        mechParam: 0.035,
        text: 'The rope snaps. It comes down running.',
      },
    ],
    lore: 'Hanged forty times by the Gallows Knights, and forty times found walking the road at dawn. On the forty-first they gave up and hanged themselves instead. It watched, and it waited, and it is very patient with those who kill on the Gallows Walk.',
  },
};
