import type { EnemyDef, AttackPattern } from './types';

// Reusable attack patterns
const A = {
  jab: (mult = 0.8): AttackPattern => ({ id: 'jab', name: 'Jab', windup: 0.7, mult, weight: 3 }),
  slash: (mult = 1.0): AttackPattern => ({ id: 'slash', name: 'Slash', windup: 0.9, mult, weight: 3 }),
  heavy: (mult = 1.8): AttackPattern => ({ id: 'heavy', name: 'Overhead', windup: 1.6, mult, weight: 1 }),
  lunge: (mult = 1.3): AttackPattern => ({ id: 'lunge', name: 'Lunge', windup: 1.1, mult, weight: 2 }),
  bite: (mult = 0.7): AttackPattern => ({ id: 'bite', name: 'Bite', windup: 0.55, mult, weight: 3 }),
  shot: (mult = 1.6): AttackPattern => ({ id: 'shot', name: 'Crossbow Bolt', windup: 1.9, mult, weight: 2 }),
  flame: (mult = 1.2): AttackPattern => ({ id: 'flame', name: 'Gout of Flame', windup: 1.3, mult, weight: 2 }),
  wail: (mult = 1.0): AttackPattern => ({ id: 'wail', name: 'Wail', windup: 1.0, mult, weight: 2 }),
  spit: (mult = 0.6): AttackPattern => ({ id: 'spit', name: 'Rot Spit', windup: 0.9, mult, weight: 2, status: 'poison' as const }),
};

export const ENEMIES: Record<string, EnemyDef> = {
  // ---------------- Region 1: The Cindered Approach ----------------
  hollowPilgrim: {
    id: 'hollowPilgrim',
    name: 'Hollow Pilgrim',
    hpMult: 1.0,
    dmgMult: 1.0,
    poiseMult: 1.0,
    attackInterval: 3.4,
    attacks: [A.jab(), A.slash()],
    resist: {},
    statusResist: {},
    soulMult: 1.0,
    drops: { shard: 0.08 },
    shape: 'humanoid',
    lore: 'They came for the flame and found only its rumour. The ones who kept walking are still walking, though the road has long since forgotten where it went.',
  },
  ashRat: {
    id: 'ashRat',
    name: 'Ash Rat',
    hpMult: 0.55,
    dmgMult: 0.6,
    poiseMult: 0.5,
    attackInterval: 2.0,
    attacks: [A.bite()],
    resist: {},
    statusResist: { poison: 0.3 },
    soulMult: 0.6,
    drops: { shard: 0.03 },
    shape: 'beast',
    lore: 'Fat on what the pilgrims left behind. Fearless, because fear is a thing you learn from surviving, and the rats of the Approach never had to.',
  },
  tollWarden: {
    id: 'tollWarden',
    name: 'Toll Warden',
    hpMult: 1.5,
    dmgMult: 0.9,
    poiseMult: 2.2,
    attackInterval: 3.8,
    attacks: [A.slash(0.9), A.heavy(1.6)],
    resist: { physical: 0.8 },
    statusResist: {},
    soulMult: 1.4,
    drops: { shard: 0.12 },
    shape: 'shield',
    lore: 'Still collecting a toll for a road that leads nowhere, on behalf of a lord who has no need of coin. The shield is dented on the inside.',
  },
  deserterCrossbow: {
    id: 'deserterCrossbow',
    name: 'Deserter Crossbowman',
    hpMult: 0.8,
    dmgMult: 1.5,
    poiseMult: 0.7,
    attackInterval: 4.5,
    attacks: [A.shot(1.7), A.jab(0.5)],
    resist: {},
    statusResist: {},
    soulMult: 1.2,
    drops: { shard: 0.08 },
    shape: 'archer',
    lore: 'He left the garrison when the pay stopped, and left his oath when the fire went out. Only the crossbow stayed with him. It is a very loyal crossbow.',
  },
  pyreHound: {
    id: 'pyreHound',
    name: 'Pyre Hound',
    hpMult: 0.9,
    dmgMult: 1.1,
    poiseMult: 0.6,
    attackInterval: 2.2,
    attacks: [A.bite(0.8), A.lunge(1.2)],
    resist: { fire: 0.5 },
    statusResist: { frost: 1.5 },
    soulMult: 1.1,
    drops: { shard: 0.1 },
    shape: 'beast',
    lore: 'Kennel-dogs of the Warden, fed on cinders until they burned from the inside. They no longer feel heat. They no longer feel much of anything, and are terribly quick.',
  },
  charredAcolyte: {
    id: 'charredAcolyte',
    name: 'Charred Acolyte',
    hpMult: 1.1,
    dmgMult: 1.3,
    poiseMult: 0.9,
    attackInterval: 3.6,
    attacks: [A.flame(1.3), A.jab(0.6)],
    resist: { fire: 0.3, magic: 1.2 },
    statusResist: { bleed: 0.5 },
    soulMult: 1.4,
    drops: { shard: 0.12, coal: 0.02 },
    shape: 'robed',
    lore: 'They prayed to the Pyre when it was warm and kept praying when it was cold. The Pyre answered the second prayer, in its way.',
  },
  gallowsKnight: {
    id: 'gallowsKnight',
    name: 'Gallows Knight',
    hpMult: 1.8,
    dmgMult: 1.5,
    poiseMult: 2.6,
    attackInterval: 4.2,
    attacks: [A.heavy(2.0), A.slash(1.1)],
    resist: { physical: 0.85 },
    statusResist: { poison: 0.6 },
    soulMult: 1.8,
    drops: { shard: 0.16, largeShard: 0.03 },
    shape: 'knight',
    lore: 'Executioners of the old lord, who hanged deserters and, when there were no deserters, pilgrims, and when there were no pilgrims, each other. The rope is still around the neck. It has never once been in the way.',
  },
  cinderWraith: {
    id: 'cinderWraith',
    name: 'Cinder Wraith',
    hpMult: 1.2,
    dmgMult: 1.2,
    poiseMult: 0.8,
    attackInterval: 3.0,
    attacks: [A.wail(1.1), A.flame(1.0)],
    resist: { physical: 0.6, magic: 1.4, fire: 0.5 },
    statusResist: { bleed: 0, poison: 0 },
    soulMult: 1.6,
    drops: { shard: 0.1, largeShard: 0.05 },
    shape: 'wraith',
    lore: 'What rises when a pyre is put out before it is finished. It has no body to bleed and no blood to poison. It has only a grudge, and grudges burn very well.',
  },
};
