import type { EnemyDef, AttackPattern } from './types';

// Reusable attack patterns
const A = {
  jab: (mult = 0.8): AttackPattern => ({ id: 'jab', name: 'Jab', windup: 0.7, mult, weight: 3 }),
  slash: (mult = 1.0): AttackPattern => ({ id: 'slash', name: 'Slash', windup: 0.9, mult, weight: 3 }),
  heavy: (mult = 1.8): AttackPattern => ({ id: 'heavy', name: 'Overhead', windup: 1.6, mult, weight: 1 }),
  lunge: (mult = 1.3): AttackPattern => ({ id: 'lunge', name: 'Lunge', windup: 1.1, mult, weight: 2 }),
  bite: (mult = 0.7): AttackPattern => ({ id: 'bite', name: 'Bite', windup: 0.55, mult, weight: 3 }),
  shot: (mult = 1.6): AttackPattern => ({ id: 'shot', name: 'Crossbow Bolt', windup: 1.9, mult, weight: 2 }),
  flame: (mult = 1.2): AttackPattern => ({ id: 'flame', name: 'Gout of Flame', windup: 1.3, mult, weight: 2 }),
  wail: (mult = 1.0): AttackPattern => ({ id: 'wail', name: 'Wail', windup: 1.0, mult, weight: 2 }),
  spit: (mult = 0.6): AttackPattern => ({ id: 'spit', name: 'Rot Spit', windup: 0.9, mult, weight: 2, status: 'poison' as const }),
};

export const ENEMIES: Record<string, EnemyDef> = {
  // ---------------- Region 1: The Tollroad ----------------
  wanedPilgrim: {
    id: 'wanedPilgrim',
    name: 'Waned Pilgrim',
    hpMult: 1.0,
    dmgMult: 1.0,
    composureMult: 1.0,
    attackInterval: 3.4,
    attacks: [A.jab(), A.slash()],
    resist: {},
    statusResist: {},
    marrowMult: 1.0,
    drops: { coarseSlag: 0.08 },
    shape: 'humanoid',
    lore: 'They came for the flame and found only its rumour. The ones who kept walking are still walking, though the road has long since forgotten where it went.',
  },
  ashRat: {
    id: 'ashRat',
    name: 'Ash Rat',
    hpMult: 0.55,
    dmgMult: 0.6,
    composureMult: 0.5,
    attackInterval: 2.0,
    attacks: [A.bite()],
    resist: {},
    statusResist: { poison: 0.3 },
    marrowMult: 0.6,
    drops: { coarseSlag: 0.03 },
    shape: 'beast',
    lore: 'Fat on what the pilgrims left behind. Fearless, because fear is a thing you learn from surviving, and the rats of the Tollroad never had to.',
  },
  tollWarden: {
    id: 'tollWarden',
    name: 'Toll Warden',
    hpMult: 1.5,
    dmgMult: 0.9,
    composureMult: 2.2,
    attackInterval: 3.8,
    attacks: [A.slash(0.9), A.heavy(1.6)],
    resist: { physical: 0.8 },
    statusResist: {},
    marrowMult: 1.4,
    drops: { coarseSlag: 0.12 },
    shape: 'shield',
    lore: 'Still collecting a toll for a road that leads nowhere, on behalf of a lord who has no need of coin. The shield is dented on the inside.',
  },
  deserterCrossbow: {
    id: 'deserterCrossbow',
    name: 'Deserter Crossbowman',
    hpMult: 0.8,
    dmgMult: 1.5,
    composureMult: 0.7,
    attackInterval: 4.5,
    attacks: [A.shot(1.7), A.jab(0.5)],
    resist: {},
    statusResist: {},
    marrowMult: 1.2,
    drops: { coarseSlag: 0.08 },
    shape: 'archer',
    lore: 'He left the garrison when the pay stopped, and left his oath when the fire went out. Only the crossbow stayed with him. It is a very loyal crossbow.',
  },
  pyreHound: {
    id: 'pyreHound',
    name: 'Pyre Hound',
    hpMult: 0.9,
    dmgMult: 1.1,
    composureMult: 0.6,
    attackInterval: 2.2,
    attacks: [A.bite(0.8), A.lunge(1.2)],
    resist: { fire: 0.5 },
    statusResist: { frost: 1.5 },
    marrowMult: 1.1,
    drops: { coarseSlag: 0.1 },
    shape: 'beast',
    lore: 'Kennel-dogs of the Warden, fed on cinders until they burned from the inside. They no longer feel heat. They no longer feel much of anything, and are terribly quick.',
  },
  charredAcolyte: {
    id: 'charredAcolyte',
    name: 'Charred Acolyte',
    hpMult: 1.1,
    dmgMult: 1.3,
    composureMult: 0.9,
    attackInterval: 3.6,
    attacks: [A.flame(1.3), A.jab(0.6)],
    resist: { fire: 0.3, magic: 1.2 },
    statusResist: { bleed: 0.5 },
    marrowMult: 1.4,
    drops: { coarseSlag: 0.12, pitchCoal: 0.02 },
    shape: 'robed',
    lore: 'They prayed to the Pyre when it was warm and kept praying when it was cold. The Pyre answered the second prayer, in its way.',
  },
  gallowsKnight: {
    id: 'gallowsKnight',
    name: 'Gallows Knight',
    hpMult: 1.8,
    dmgMult: 1.5,
    composureMult: 2.6,
    attackInterval: 4.2,
    attacks: [A.heavy(2.0), A.slash(1.1)],
    resist: { physical: 0.85 },
    statusResist: { poison: 0.6 },
    marrowMult: 1.8,
    drops: { coarseSlag: 0.16, fineSlag: 0.03 },
    shape: 'knight',
    lore: 'Executioners of the old lord, who hanged deserters and, when there were no deserters, pilgrims, and when there were no pilgrims, each other. The rope is still around the neck. It has never once been in the way.',
  },
  tallowWraith: {
    id: 'tallowWraith',
    name: 'Tallow Wraith',
    hpMult: 1.2,
    dmgMult: 1.2,
    composureMult: 0.8,
    attackInterval: 3.0,
    attacks: [A.wail(1.1), A.flame(1.0)],
    resist: { physical: 0.6, magic: 1.4, fire: 0.5 },
    statusResist: { bleed: 0, poison: 0 },
    marrowMult: 1.6,
    drops: { coarseSlag: 0.1, fineSlag: 0.05 },
    shape: 'wraith',
    lore: 'What rises when a pyre is put out before it is finished. It has no body to bleed and no blood to poison. It has only a grudge, and grudges burn very well.',
  },
};

// ---------------- Region 2: The Drowned Mire ----------------
Object.assign(ENEMIES, {
  bogLeech: {
    id: 'bogLeech', name: 'Bog Leech', hpMult: 0.6, dmgMult: 0.7, composureMult: 0.4, attackInterval: 2.4,
    attacks: [A.bite(0.6), A.spit(0.5)], resist: { fire: 1.4 }, statusResist: { poison: 0, bleed: 1.5 }, marrowMult: 0.7,
    drops: { coarseSlag: 0.06, fineSlag: 0.02 }, shape: 'beast',
    lore: 'Grown fat on the drowned. It has no eyes and needs none; it knows where you are by the hearth, and it has never once been wrong.',
  },
  mireWaned: {
    id: 'mireWaned', name: 'Mire Waned', hpMult: 1.0, dmgMult: 1.0, composureMult: 1.0, attackInterval: 3.2,
    attacks: [A.slash(1.0), A.spit(0.7)], resist: { fire: 1.3 }, statusResist: { poison: 0.2 }, marrowMult: 1.0,
    drops: { coarseSlag: 0.1, fineSlag: 0.04 }, shape: 'humanoid',
    lore: 'A pilgrim who reached the Mire and lay down in it. The water kept what the fire would have taken. It still has most of a face.',
  },
  rottingKnight: {
    id: 'rottingKnight', name: 'Rotting Knight', hpMult: 1.7, dmgMult: 1.3, composureMult: 2.4, attackInterval: 4.0,
    attacks: [A.heavy(1.9), A.slash(1.1)], resist: { physical: 0.85, fire: 1.3 }, statusResist: { poison: 0, bleed: 0.6 }, marrowMult: 1.6,
    drops: { fineSlag: 0.1, coarseSlag: 0.08 }, shape: 'knight',
    lore: 'Armour holds a knight together long after the knight has stopped holding anything. The rot inside has learned to swing a sword. It swings it badly, and very hard.',
  },
  drownedChorister: {
    id: 'drownedChorister', name: 'Drowned Chorister', hpMult: 0.9, dmgMult: 1.4, composureMult: 0.7, attackInterval: 3.8,
    attacks: [A.wail(1.3), A.jab(0.5)], resist: { physical: 0.7, magic: 1.3, lightning: 0.6 }, statusResist: { bleed: 0, frost: 1.4 }, marrowMult: 1.5,
    drops: { fineSlag: 0.08, pitchCoal: 0.02 }, shape: 'wraith',
    lore: 'The Sunken Chapel\'s choir, still singing. The water carries the hymn a long way. Those who follow it arrive at the choir, and then, some time later, join it.',
  },
  fenStalker: {
    id: 'fenStalker', name: 'Fen Stalker', hpMult: 1.1, dmgMult: 1.5, composureMult: 0.9, attackInterval: 2.6,
    attacks: [A.lunge(1.5), A.bite(0.8)], resist: { magic: 0.8 }, statusResist: { frost: 1.3 }, marrowMult: 1.4,
    drops: { fineSlag: 0.09, coarseSlag: 0.05 }, shape: 'beast',
    lore: 'Something that was a hound, before the Mire, and is now mostly teeth and patience. It waits under the reeds. It can wait longer than you can stand still.',
  },
  rotwoodTreant: {
    id: 'rotwoodTreant', name: 'Rotwood Warden', hpMult: 2.2, dmgMult: 1.6, composureMult: 3.0, attackInterval: 4.6,
    attacks: [A.heavy(2.2), { id: 'sweep', name: 'Root Sweep', windup: 1.4, mult: 1.4, weight: 2 }], resist: { physical: 0.8, fire: 1.6, magic: 0.9 }, statusResist: { poison: 0, bleed: 0.4, frost: 1.2 }, marrowMult: 2.2,
    drops: { fineSlag: 0.14, pitchCoal: 0.03 }, shape: 'knight',
    lore: 'A tree that drank from the Mire for a century and grew a grudge. It moves slowly, which is a mercy, and hits like a falling tree, which is not.',
  },
  // ---------------- Region 3: The Archive of Null ----------------
  archiveScribe: {
    id: 'archiveScribe', name: 'Archive Scribe', hpMult: 0.7, dmgMult: 1.3, composureMult: 0.5, attackInterval: 3.4,
    attacks: [{ id: 'bolt', name: 'Marrow Bolt', windup: 1.2, mult: 1.3, weight: 3 }, A.jab(0.4)], resist: { magic: 0.6, physical: 1.1 }, statusResist: {}, marrowMult: 1.1,
    drops: { fineSlag: 0.08, pitchCoal: 0.02 }, shape: 'robed',
    lore: 'Copyists who copied until the copying was all that was left of them. Their bolts are quotations. They have not had an original thought in an age, and they resent yours.',
  },
  boundTome: {
    id: 'boundTome', name: 'Bound Tome', hpMult: 0.8, dmgMult: 1.1, composureMult: 0.6, attackInterval: 2.8,
    attacks: [{ id: 'snap', name: 'Snap', windup: 0.7, mult: 0.9, weight: 3 }, { id: 'page', name: 'Page Storm', windup: 1.3, mult: 1.4, weight: 1 }], resist: { magic: 0.3, fire: 1.8, physical: 1.0 }, statusResist: { bleed: 0, poison: 0 }, marrowMult: 1.2,
    drops: { fineSlag: 0.08 }, shape: 'wraith',
    lore: 'A book chained shut, which is not the same as a book closed. Whatever is written inside wants very badly to be read, and has found a way to turn its own pages.',
  },
  nullCustodian: {
    id: 'nullCustodian', name: 'Null Custodian', hpMult: 1.9, dmgMult: 1.3, composureMult: 2.8, attackInterval: 4.2,
    attacks: [A.heavy(1.9), A.slash(1.0)], resist: { physical: 0.6, magic: 1.3, lightning: 1.2 }, statusResist: { poison: 0.5, frost: 0.7 }, marrowMult: 1.8,
    drops: { fineSlag: 0.12, blackSlag: 0.02 }, shape: 'shield',
    lore: 'Armoured in plates inscribed with the one word the Archive was built to protect. No one may read it. The custodians have long since stopped being able to.',
  },
  crystalWaned: {
    id: 'crystalWaned', name: 'Glass Waned', hpMult: 1.2, dmgMult: 1.4, composureMult: 1.2, attackInterval: 3.4,
    attacks: [{ id: 'coarseSlag', name: 'Glass Splinter', windup: 1.0, mult: 1.3, weight: 3 }, A.slash(1.0)], resist: { magic: 0.5, physical: 0.9, fire: 1.3 }, statusResist: { frost: 0, bleed: 0.5 }, marrowMult: 1.5,
    drops: { fineSlag: 0.1, blackSlag: 0.03 }, shape: 'humanoid',
    lore: 'Sorcerers who studied the crystal until the crystal studied them back. They no longer feel the cold. They are, in the most literal sense, the cold.',
  },
  silencedScholar: {
    id: 'silencedScholar', name: 'Silenced Scholar', hpMult: 1.0, dmgMult: 1.7, composureMult: 0.8, attackInterval: 3.8,
    attacks: [{ id: 'unword', name: 'Unword', windup: 1.6, mult: 2.0, weight: 2 }, A.jab(0.5)], resist: { magic: 0.7, dark: 0.5 }, statusResist: { bleed: 0.8 }, marrowMult: 1.7,
    drops: { fineSlag: 0.1, blackSlag: 0.03, pitchCoal: 0.03 }, shape: 'robed',
    lore: 'They read the word. The Archive removed their mouths, as it must. It did not think to remove their hands, and the hands remember how to write it in the air.',
  },
  // ---------------- Region 4: The Sanctum of the Vigil ----------------
  vigilAcolyte: {
    id: 'vigilAcolyte', name: 'Vigil Acolyte', hpMult: 0.9, dmgMult: 1.1, composureMult: 0.8, attackInterval: 3.2,
    attacks: [A.slash(1.0), { id: 'spark', name: 'Spark', windup: 1.0, mult: 1.2, weight: 2 }], resist: { lightning: 0.5 }, statusResist: {}, marrowMult: 1.0,
    drops: { fineSlag: 0.06, blackSlag: 0.04 }, shape: 'robed',
    lore: 'Initiates of the Vigil, keeping a watch that was supposed to last a night and has lasted an age. They are very tired, and very devout, and both make them dangerous.',
  },
  sanctumKnight: {
    id: 'sanctumKnight', name: 'Sanctum Knight', hpMult: 1.8, dmgMult: 1.5, composureMult: 2.6, attackInterval: 3.8,
    attacks: [{ id: 'thrust', name: 'Lightning Thrust', windup: 1.1, mult: 1.6, weight: 3 }, A.heavy(2.0)], resist: { lightning: 0.4, physical: 0.8, dark: 1.3 }, statusResist: { poison: 0.5 }, marrowMult: 1.7,
    drops: { blackSlag: 0.08, fineSlag: 0.06 }, shape: 'knight',
    lore: 'Knights sworn to the Lantern. Their spears carry the storm. They believe that when the Vigil ends the sun will rise, and they intend to be standing when it does.',
  },
  lanternBearer: {
    id: 'lanternBearer', name: 'Lantern Bearer', hpMult: 1.1, dmgMult: 1.2, composureMult: 1.0, attackInterval: 3.6,
    attacks: [{ id: 'flare', name: 'Lantern Flare', windup: 1.4, mult: 1.5, weight: 2 }, A.jab(0.6)], resist: { lightning: 0.5, fire: 0.7, dark: 1.5 }, statusResist: { frost: 0.6 }, marrowMult: 1.5,
    drops: { blackSlag: 0.06, pitchCoal: 0.03 }, shape: 'robed',
    lore: 'Each carries a lantern lit from the Warden\'s own. The light does not warm. It sees. Those it sees, it does not forget, and it tells the knights.',
  },
  stormGargoyle: {
    id: 'stormGargoyle', name: 'Storm Gargoyle', hpMult: 1.3, dmgMult: 1.4, composureMult: 1.4, attackInterval: 2.6,
    attacks: [A.lunge(1.3), { id: 'tail', name: 'Tail Lash', windup: 0.8, mult: 1.0, weight: 3 }], resist: { physical: 0.7, lightning: 0.3 }, statusResist: { frost: 0, bleed: 0, poison: 0 }, marrowMult: 1.6,
    drops: { blackSlag: 0.08 }, shape: 'beast',
    lore: 'Stone that the storm got into. It perches on the Sanctum walls and comes down on anything the lanterns point at. It does not bleed, poison, or freeze. It is, after all, a wall.',
  },
  deaconOfStorms: {
    id: 'deaconOfStorms', name: 'Deacon of Storms', hpMult: 1.4, dmgMult: 1.9, composureMult: 1.1, attackInterval: 4.2,
    attacks: [{ id: 'bolt', name: 'Storm Bolt', windup: 1.7, mult: 2.4, weight: 2 }, { id: 'spark', name: 'Spark', windup: 0.9, mult: 1.0, weight: 2 }], resist: { lightning: 0.3, dark: 1.4 }, statusResist: {}, marrowMult: 1.9,
    drops: { blackSlag: 0.09, pitchCoal: 0.03 }, shape: 'robed',
    lore: 'Priests who call the storm down and are, in return, allowed to keep standing near it. Their sermons are short and mostly thunder.',
  },
  silverSentinel: {
    id: 'silverSentinel', name: 'Silver Sentinel', hpMult: 2.6, dmgMult: 1.6, composureMult: 3.6, attackInterval: 4.8,
    attacks: [A.heavy(2.4), { id: 'sweep', name: 'Halberd Sweep', windup: 1.5, mult: 1.6, weight: 2 }], resist: { physical: 0.55, lightning: 0.6, magic: 1.1, dark: 1.2 }, statusResist: { poison: 0.3, bleed: 0.5 }, marrowMult: 2.4,
    drops: { blackSlag: 0.14, slagIngot: 0.005 }, shape: 'shield',
    lore: 'Revenant suits of silver, animated by the Vigil\'s oath alone. Nothing inside to poison or bleed. Only the oath, which is stubborn, and the halberd, which is sharp.',
  },
  // ---------------- Region 5: The Deep ----------------
  nadirCrawler: {
    id: 'nadirCrawler', name: 'Nadir Crawler', hpMult: 0.8, dmgMult: 1.2, composureMult: 0.6, attackInterval: 2.2,
    attacks: [A.bite(0.9), A.lunge(1.3)], resist: { dark: 0.4, lightning: 1.3 }, statusResist: { bleed: 1.3 }, marrowMult: 1.0,
    drops: { blackSlag: 0.06 }, shape: 'beast',
    lore: 'What vestige becomes when it has nothing left to be human about. Many legs. Many eyes, none of them looking at anything in particular. It is very fast in the dark.',
  },
  vestigeWisp: {
    id: 'vestigeWisp', name: 'Vestige Wisp', hpMult: 0.5, dmgMult: 1.6, composureMult: 0.3, attackInterval: 2.0,
    attacks: [{ id: 'cling', name: 'Cling', windup: 0.6, mult: 1.2, weight: 3 }], resist: { physical: 0.5, dark: 0, magic: 0.8 }, statusResist: { bleed: 0, poison: 0, frost: 0 }, marrowMult: 2.2,
    drops: { blackSlag: 0.05, dust: 0.003 }, shape: 'wraith',
    lore: 'A small black shape with a whiteness at its centre. It wants to be held. Those who hold it are found later, smiling, and empty. It is worth a great many marrow, which should tell you something.',
  },
  undercroftWaned: {
    id: 'undercroftWaned', name: 'Undercroft Waned', hpMult: 1.2, dmgMult: 1.3, composureMult: 1.1, attackInterval: 3.0,
    attacks: [A.slash(1.1), { id: 'grasp', name: 'Grasp', windup: 1.2, mult: 1.6, weight: 2 }], resist: { dark: 0.5, fire: 0.8 }, statusResist: { poison: 0.5 }, marrowMult: 1.3,
    drops: { blackSlag: 0.09, fineSlag: 0.05 }, shape: 'humanoid',
    lore: 'Revenants that went down instead of up. The dark did not take them. It kept them, the way a cellar keeps a thing, and it has had a long time to make adjustments.',
  },
  shadowOfTheLost: {
    id: 'shadowOfTheLost', name: 'Shadow of the Lost', hpMult: 1.4, dmgMult: 1.5, composureMult: 0.9, attackInterval: 3.4,
    attacks: [A.wail(1.4), { id: 'reach', name: 'Reach', windup: 1.0, mult: 1.2, weight: 2 }], resist: { magic: 0.3, dark: 0.3, physical: 1.0, fire: 1.4 }, statusResist: { frost: 0, bleed: 0 }, marrowMult: 1.8,
    drops: { blackSlag: 0.1, pitchCoal: 0.03 }, shape: 'wraith',
    lore: 'Not a ghost. The shape a person leaves in the dark when the dark closes over them. Spells pass through it as through smoke. Fire, which the dark remembers, does not.',
  },
  paleGaoler: {
    id: 'paleGaoler', name: 'Pale Gaoler', hpMult: 2.0, dmgMult: 1.7, composureMult: 2.8, attackInterval: 4.4,
    attacks: [{ id: 'brand', name: 'Brand', windup: 1.5, mult: 2.0, weight: 2 }, A.heavy(2.2)], resist: { physical: 0.7, dark: 0.6, lightning: 1.2 }, statusResist: { poison: 0.4, bleed: 0.7 }, marrowMult: 2.1,
    drops: { blackSlag: 0.12, slagIngot: 0.006 }, shape: 'knight',
    lore: 'Keepers of the Deep\'s cells. Their brands mark the prisoner, and the mark is what the dark uses to find them again. Nobody has ever been released. Nobody has ever asked.',
  },
  undercroftKnight: {
    id: 'undercroftKnight', name: 'Knight of the Undercroft', hpMult: 2.4, dmgMult: 1.9, composureMult: 3.2, attackInterval: 4.0,
    attacks: [{ id: 'darkthrust', name: 'Dark Thrust', windup: 1.1, mult: 1.9, weight: 3 }, A.heavy(2.6)], resist: { dark: 0.3, physical: 0.75, lightning: 1.3 }, statusResist: { bleed: 0.6 }, marrowMult: 2.6,
    drops: { blackSlag: 0.14, slagIngot: 0.008, pitchCoal: 0.03 }, shape: 'knight',
    lore: 'Knights who came to end the dark and were ended by it, and then rose to guard the thing they came to kill. Their swords are wet with a darkness that never dries.',
  },
  // ---------------- Region 6: The Rendering Works ----------------
  renderKnight: {
    id: 'renderKnight', name: 'Render Knight', hpMult: 2.0, dmgMult: 1.7, composureMult: 2.8, attackInterval: 3.6,
    attacks: [{ id: 'cinder', name: 'Tallow Slash', windup: 1.0, mult: 1.7, weight: 3 }, A.heavy(2.4)], resist: { fire: 0.3, physical: 0.8 }, statusResist: { frost: 0.5, bleed: 0.8 }, marrowMult: 2.0,
    drops: { blackSlag: 0.12, slagIngot: 0.008 }, shape: 'knight',
    lore: 'The Lord\'s own guard, standing in the fire so long the fire stopped noticing them. Their armour glows at the joints. They do not feel it. They feel very little now, except duty.',
  },
  tallowDrake: {
    id: 'tallowDrake', name: 'Tallow Drake', hpMult: 1.6, dmgMult: 1.9, composureMult: 1.5, attackInterval: 3.0,
    attacks: [{ id: 'breath', name: 'Wick Breath', windup: 1.5, mult: 2.2, weight: 2 }, A.bite(1.1), { id: 'tail', name: 'Tail Lash', windup: 0.8, mult: 1.2, weight: 2 }], resist: { fire: 0.2, magic: 0.9 }, statusResist: { frost: 1.5, poison: 0.4 }, marrowMult: 2.2,
    drops: { blackSlag: 0.12, pitchCoal: 0.04 }, shape: 'beast',
    lore: 'What is left of the dragons: small, furious, and on fire. They nest in the Rendering Works because it is the only place still hot enough to feel like home.',
  },
  pyreGolem: {
    id: 'pyreGolem', name: 'Pyre Golem', hpMult: 3.0, dmgMult: 2.0, composureMult: 4.0, attackInterval: 5.0,
    attacks: [A.heavy(2.8), { id: 'slam', name: 'Slam', windup: 2.0, mult: 3.2, weight: 1 }], resist: { physical: 0.5, fire: 0.4, magic: 1.2 }, statusResist: { poison: 0, bleed: 0, frost: 1.3 }, marrowMult: 2.8,
    drops: { blackSlag: 0.16, slagIngot: 0.012 }, shape: 'shield',
    lore: 'Built from the Rendering Works\'s own bricks by hands that wanted a guardian that would never tire. It never has. It is not clever, and it does not need to be. It is a wall that walks.',
  },
  ashWraith: {
    id: 'ashWraith', name: 'Ash Wraith', hpMult: 1.4, dmgMult: 1.6, composureMult: 0.9, attackInterval: 2.8,
    attacks: [A.wail(1.5), { id: 'engulf', name: 'Engulf', windup: 1.2, mult: 1.9, weight: 2 }], resist: { physical: 0.5, fire: 0.6, magic: 1.2, dark: 1.3 }, statusResist: { bleed: 0, poison: 0 }, marrowMult: 2.0,
    drops: { blackSlag: 0.1, pitchCoal: 0.04 }, shape: 'wraith',
    lore: 'The ash of everything the Rendering Works has burned, given a shape by wanting one. It is many people. It does not agree with itself about much, except that you should be ash too.',
  },
  brandShepherd: {
    id: 'brandShepherd', name: 'Brand Shepherd', hpMult: 1.8, dmgMult: 2.2, composureMult: 1.6, attackInterval: 4.0,
    attacks: [{ id: 'crook', name: 'Crook', windup: 1.1, mult: 1.6, weight: 3 }, { id: 'rendering', name: 'Rendering', windup: 1.8, mult: 2.8, weight: 1 }], resist: { fire: 0.3, dark: 0.7, lightning: 1.2 }, statusResist: { frost: 0.4 }, marrowMult: 2.5,
    drops: { blackSlag: 0.12, slagIngot: 0.01, pitchCoal: 0.05 }, shape: 'robed',
    lore: 'They tend the Lord\'s fire the way a shepherd tends a flock, with a crook and no sentiment. New fuel is brought to them. They do not ask where it came from. Sometimes it asks them.',
  },
  lordsRemnant: {
    id: 'lordsRemnant', name: 'Remnant of the Renderer', hpMult: 2.6, dmgMult: 2.4, composureMult: 3.0, attackInterval: 3.4,
    attacks: [{ id: 'cinder', name: 'Tallow Slash', windup: 0.9, mult: 1.9, weight: 3 }, { id: 'rendering', name: 'Rendering', windup: 1.6, mult: 3.0, weight: 1 }], resist: { fire: 0.2, physical: 0.7, dark: 0.8 }, statusResist: { frost: 0.5, poison: 0.5 }, marrowMult: 3.2,
    drops: { blackSlag: 0.15, slagIngot: 0.015, pitchCoal: 0.05 }, shape: 'warden',
    lore: 'Pieces of the Lord that fell off along the way and kept walking. Each is a little of him: the pride, the fire, the certainty. None of them is enough to be him. All of them think they are.',
  },
} satisfies Record<string, EnemyDef>);
