import type { WeaponDef } from './types';

/**
 * Weapon roster. Archetypes: fast (low stamina, high click value, big ripostes),
 * heavy (slow, huge per-hit, builds stagger), hybrid, catalyst (spellcasting).
 */
export const WEAPONS: Record<string, WeaponDef> = {
  hollowSword: {
    id: 'hollowSword',
    name: 'Hollow Straight Sword',
    archetype: 'hybrid',
    base: 11,
    damageType: 'physical',
    stamina: 9,
    stagger: 6,
    riposteMult: 3,
    crit: 0,
    scaling: { str: 'D', dex: 'D' },
    req: {},
    infusable: true,
    source: { kind: 'start' },
    speed: 1.0,
    region: 1,
    lore: 'The sword every hollow carries, because every hollow was once given one. Notched, honest, unremarkable. It will outlast you, and then someone else will carry it.',
  },
  banditDagger: {
    id: 'banditDagger',
    name: 'Bandit Dagger',
    archetype: 'fast',
    base: 7,
    damageType: 'physical',
    stamina: 5,
    stagger: 3,
    riposteMult: 5,
    crit: 0.08,
    scaling: { dex: 'C', str: 'E' },
    req: { dex: 10 },
    status: { bleed: 7 },
    infusable: true,
    source: { kind: 'shop', cost: 120, region: 1 },
    speed: 1.6,
    region: 1,
    lore: 'Curved for the ribs, not the plate. The bandits of the Approach did not fight the knights; they waited until the knights were tired. A wise philosophy, and a short life.',
  },
  pilgrimMace: {
    id: 'pilgrimMace',
    name: "Pilgrim's Mace",
    archetype: 'heavy',
    base: 19,
    damageType: 'physical',
    stamina: 17,
    stagger: 14,
    riposteMult: 2.4,
    crit: 0,
    scaling: { str: 'C' },
    req: { str: 12 },
    infusable: true,
    source: { kind: 'shop', cost: 150, region: 1 },
    speed: 0.7,
    region: 1,
    lore: 'A walking staff that ends in an iron fist. The pilgrims were told the road was safe. The mace suggests they were told a great many things.',
  },
  deserterSpear: {
    id: 'deserterSpear',
    name: "Deserter's Spear",
    archetype: 'hybrid',
    base: 13,
    damageType: 'physical',
    stamina: 10,
    stagger: 8,
    riposteMult: 3,
    crit: 0.03,
    scaling: { dex: 'C', str: 'E' },
    req: { dex: 11 },
    infusable: true,
    source: { kind: 'drop', zone: 'approach', tier: 1, chance: 0.06 },
    speed: 1.1,
    region: 1,
    lore: 'Standard issue for the Toll Gate garrison. Its former owner filed off the regimental mark and did not get far. The reach is good; the reach was never the problem.',
  },
  wardenCleaver: {
    id: 'wardenCleaver',
    name: "Warden's Cleaver",
    archetype: 'heavy',
    base: 30,
    damageType: 'fire',
    stamina: 19,
    stagger: 17,
    riposteMult: 2.6,
    crit: 0,
    scaling: { str: 'B', fth: 'E' },
    req: { str: 16 },
    infusable: false,
    source: { kind: 'bossSoul', boss: 'coldPyreWarden' },
    speed: 0.65,
    region: 1,
    lore: 'The cleaver of the Warden who kept the Cold Pyre. It still burns at the edge, though the Pyre is ash. Fire, it seems, needs no reason to keep going. Only something to eat.',
  },
};

export const STARTING_WEAPON = 'hollowSword';

WEAPONS.gallowsRope = {
  id: 'gallowsRope',
  name: 'Gallows Rope',
  archetype: 'fast',
  base: 9,
  damageType: 'physical',
  stamina: 6,
  stagger: 4,
  riposteMult: 4.5,
  crit: 0.06,
  scaling: { dex: 'B' },
  req: { dex: 14 },
  status: { bleed: 16 },
  infusable: false,
  source: { kind: 'bossSoul', boss: 'hangedPilgrim' },
  speed: 1.5,
  region: 1,
  lore: 'A length of rope, still knotted, still tight. Used as a garrotte it opens the throat rather than closing it. The Pilgrim knew exactly what it was for.',
};
