import type { WeaponDef } from './types';

/**
 * Weapon roster. Archetypes: fast (low stamina, high click value, big reprisals),
 * heavy (slow, huge per-hit, builds strain), hybrid, catalyst (spellcasting).
 */
export const WEAPONS: Record<string, WeaponDef> = {
  revenantSword: {
    id: 'revenantSword',
    name: 'Revenant\'s Straight Sword',
    archetype: 'hybrid',
    base: 11,
    damageType: 'physical',
    stamina: 9,
    strain: 6,
    reprisalMult: 3,
    crit: 0,
    scaling: { mig: 'D', fin: 'D' },
    req: {},
    infusable: true,
    source: { kind: 'start' },
    speed: 1.0,
    region: 1,
    lore: 'The sword every revenant carries, because every revenant was once given one. Notched, honest, unremarkable. It will outlast you, and then someone else will carry it.',
  },
  banditDagger: {
    id: 'banditDagger',
    name: 'Bandit Dagger',
    archetype: 'fast',
    base: 7,
    damageType: 'physical',
    stamina: 5,
    strain: 3,
    reprisalMult: 5,
    crit: 0.08,
    scaling: { fin: 'C', mig: 'E' },
    req: { fin: 10 },
    status: { bleed: 7 },
    infusable: true,
    source: { kind: 'shop', cost: 120, region: 1 },
    speed: 1.6,
    region: 1,
    lore: 'Curved for the ribs, not the plate. The bandits of the Tollroad did not fight the knights; they waited until the knights were tired. A wise philosophy, and a short life.',
  },
  pilgrimMace: {
    id: 'pilgrimMace',
    name: "Pilgrim's Mace",
    archetype: 'heavy',
    base: 19,
    damageType: 'physical',
    stamina: 17,
    strain: 14,
    reprisalMult: 2.4,
    crit: 0,
    scaling: { mig: 'C' },
    req: { mig: 12 },
    infusable: true,
    source: { kind: 'shop', cost: 150, region: 1 },
    speed: 0.7,
    region: 1,
    lore: 'A walking staff that ends in an iron fist. The pilgrims were told the road was safe. The mace suggests they were told a great many things.',
  },
  deserterSpear: {
    id: 'deserterSpear',
    name: "Deserter's Spear",
    archetype: 'hybrid',
    base: 13,
    damageType: 'physical',
    stamina: 10,
    strain: 8,
    reprisalMult: 3,
    crit: 0.03,
    scaling: { fin: 'C', mig: 'E' },
    req: { fin: 11 },
    infusable: true,
    source: { kind: 'drop', zone: 'tollroad', tier: 1, chance: 0.06 },
    speed: 1.1,
    region: 1,
    lore: 'Standard issue for the Toll Gate garrison. Its former owner filed off the regimental mark and did not get far. The reach is good; the reach was never the problem.',
  },
  wardenCleaver: {
    id: 'wardenCleaver',
    name: "Warden's Cleaver",
    archetype: 'heavy',
    base: 30,
    damageType: 'fire',
    stamina: 19,
    strain: 17,
    reprisalMult: 2.6,
    crit: 0,
    scaling: { mig: 'B', dev: 'E' },
    req: { mig: 16 },
    infusable: false,
    source: { kind: 'keepsake', boss: 'coldPyreWarden' },
    speed: 0.65,
    region: 1,
    lore: 'The cleaver of the Warden who kept the Cold Pyre. It still burns at the edge, though the Pyre is ash. Fire, it seems, needs no reason to keep going. Only something to eat.',
  },
};

export const STARTING_WEAPON = 'revenantSword';

WEAPONS.gallowsRope = {
  id: 'gallowsRope',
  name: 'Gallows Rope',
  archetype: 'fast',
  base: 9,
  damageType: 'physical',
  stamina: 6,
  strain: 4,
  reprisalMult: 4.5,
  crit: 0.06,
  scaling: { fin: 'B' },
  req: { fin: 14 },
  status: { bleed: 16 },
  infusable: false,
  source: { kind: 'keepsake', boss: 'hangedPilgrim' },
  speed: 1.5,
  region: 1,
  lore: 'A length of rope, still knotted, still tight. Used as a garrotte it opens the throat rather than closing it. The Pilgrim knew exactly what it was for.',
};

// ---------------- Catalysts ----------------
WEAPONS.weaverStaff = {
  id: 'weaverStaff',
  name: 'Weaver\'s Staff',
  archetype: 'catalyst',
  base: 6,
  damageType: 'magic',
  stamina: 7,
  strain: 3,
  reprisalMult: 2,
  crit: 0,
  scaling: { ins: 'B' },
  req: { ins: 10 },
  infusable: false,
  source: { kind: 'shop', cost: 260, region: 1 },
  speed: 1.0,
  region: 1,
  lore: 'A staff of ash-wood, waned and filled with the ash of something else. Owning it opens one recitation slot. Wielding it channels weaving: +25% weaving power, and a poor excuse for a club.',
};
WEAPONS.litanyBeads = {
  id: 'litanyBeads',
  name: 'Litany Beads',
  archetype: 'catalyst',
  base: 6,
  damageType: 'lightning',
  stamina: 7,
  strain: 3,
  reprisalMult: 2,
  crit: 0,
  scaling: { dev: 'B' },
  req: { dev: 10 },
  infusable: false,
  source: { kind: 'shop', cost: 260, region: 1 },
  speed: 1.0,
  region: 1,
  lore: 'A holy symbol, cracked down the middle by a prayer that was not answered gently. Owning it opens one recitation slot. Wielding it channels litanies: +25% litany power.',
};
WEAPONS.ruinBrand = {
  id: 'ruinBrand',
  name: 'Ruin Brand',
  archetype: 'catalyst',
  base: 8,
  damageType: 'fire',
  stamina: 6,
  strain: 3,
  reprisalMult: 2,
  crit: 0,
  scaling: { ins: 'E', dev: 'E' },
  req: {},
  infusable: false,
  source: { kind: 'shop', cost: 900, region: 2 },
  speed: 1.0,
  region: 2,
  lore: 'A flame that lives in the palm and feeds on marrow. It grows with what you pour into it, and asks nothing of your mind or your devotion. Owning it opens one recitation slot; wielding it channels ruin: +25% power.',
};

// ---------------- Region 2: The Drowned Mire ----------------
Object.assign(WEAPONS, {
  rotwoodClub: {
    id: 'rotwoodClub', name: 'Rotwood Club', archetype: 'heavy', base: 62, damageType: 'physical', stamina: 18, strain: 15, reprisalMult: 2.4, crit: 0,
    scaling: { mig: 'C' }, req: { mig: 16 }, status: { poison: 12 }, infusable: true, source: { kind: 'shop', cost: 2600, region: 2 }, speed: 0.7, region: 2,
    lore: 'A branch of the Rotwood, still wet. Whatever it hits, the Mire gets into. It is not a subtle weapon, and the Mire is not a subtle place.',
  },
  fenRapier: {
    id: 'fenRapier', name: 'Fen Rapier', archetype: 'fast', base: 30, damageType: 'physical', stamina: 6, strain: 4, reprisalMult: 4.5, crit: 0.08,
    scaling: { fin: 'B' }, req: { fin: 18 }, infusable: true, source: { kind: 'shop', cost: 2400, region: 2 }, speed: 1.5, region: 2,
    lore: 'A duelling blade from a court that sank. The etiquette of its use survives in the wrist: strike, withdraw, strike. The court itself does not.',
  },
  drownedHalberd: {
    id: 'drownedHalberd', name: 'Drowned Halberd', archetype: 'hybrid', base: 52, damageType: 'physical', stamina: 12, strain: 10, reprisalMult: 3, crit: 0.03,
    scaling: { mig: 'C', fin: 'D' }, req: { mig: 14, fin: 12 }, infusable: true, source: { kind: 'drop', zone: 'mire', tier: 3, chance: 0.05 }, speed: 1.0, region: 2,
    lore: 'Carried by the Rotting Knights, who have forgotten how to hold it properly and so hold it very tightly. Pried from a hand that took some prying.',
  },
  mothersThorn: {
    id: 'mothersThorn', name: 'Mother\'s Thorn', archetype: 'fast', base: 38, damageType: 'physical', stamina: 6, strain: 5, reprisalMult: 4.5, crit: 0.05,
    scaling: { fin: 'B', ins: 'E' }, req: { fin: 20 }, status: { poison: 22 }, infusable: false, source: { kind: 'keepsake', boss: 'mireMother' }, speed: 1.5, region: 2,
    lore: 'A thorn from the crown of Mother Nettle, long as a forearm and revenant. Whatever it pierces, the Mire drinks from. It is, technically, a gift. She would have wanted you to have it.',
  },
  bellHammer: {
    id: 'bellHammer', name: 'Bell-Hammer', archetype: 'heavy', base: 78, damageType: 'lightning', stamina: 20, strain: 18, reprisalMult: 2.6, crit: 0,
    scaling: { mig: 'B', dev: 'D' }, req: { mig: 20, dev: 10 }, infusable: false, source: { kind: 'keepsake', boss: 'choirMaster' }, speed: 0.62, region: 2,
    lore: 'The Choir-Master\'s tuning hammer, which struck the chapel bell to give the choir their note. The bell is under the water now. The hammer still rings when it lands, and the note is still true.',
  },
  // ---------------- Region 3: The Archive of Null ----------------
  scholarsEstoc: {
    id: 'scholarsEstoc', name: 'Scholar\'s Estoc', archetype: 'fast', base: 130, damageType: 'magic', stamina: 7, strain: 5, reprisalMult: 4, crit: 0.06,
    scaling: { fin: 'C', ins: 'C' }, req: { fin: 18, ins: 16 }, infusable: true, source: { kind: 'shop', cost: 40000, region: 3 }, speed: 1.4, region: 3,
    lore: 'The Archive\'s scholars were forbidden weapons. They were not forbidden pens. This is the point to which the argument was eventually taken.',
  },
  custodianGreatmace: {
    id: 'custodianGreatmace', name: 'Custodian\'s Greatmace', archetype: 'heavy', base: 300, damageType: 'physical', stamina: 21, strain: 20, reprisalMult: 2.4, crit: 0,
    scaling: { mig: 'B' }, req: { mig: 26 }, infusable: true, source: { kind: 'shop', cost: 48000, region: 3 }, speed: 0.6, region: 3,
    lore: 'Issued to the custodians for the removal of unauthorised readers. Its head is inscribed with the shelf number of the word. Nobody can read it anymore, which is the intention.',
  },
  glassSword: {
    id: 'glassSword', name: 'Glass Straight Sword', archetype: 'hybrid', base: 220, damageType: 'magic', stamina: 10, strain: 8, reprisalMult: 3, crit: 0.03,
    scaling: { ins: 'B', fin: 'D' }, req: { ins: 20 }, status: { frost: 10 }, infusable: false, source: { kind: 'drop', zone: 'archive', tier: 3, chance: 0.05 }, speed: 1.1, region: 3,
    lore: 'A sword grown rather than forged, in the Crystal Cloister, from a seed of Marrow. It is cold to hold and colder to be held by. It chips. The chips grow back.',
  },
  nullBlade: {
    id: 'nullBlade', name: 'Null Blade', archetype: 'hybrid', base: 290, damageType: 'magic', stamina: 11, strain: 9, reprisalMult: 3.2, crit: 0.04,
    scaling: { ins: 'A', fin: 'D' }, req: { ins: 24 }, infusable: false, source: { kind: 'keepsake', boss: 'archivistNull' }, speed: 1.1, region: 3,
    lore: 'The Archivist\'s letter-opener, if a letter could be a person. Its edge is the word, and the word unmakes. He never drew it on a reader. He never had to.',
  },
  unwrittenEdge: {
    id: 'unwrittenEdge', name: 'Unwritten Edge', archetype: 'fast', base: 170, damageType: 'magic', stamina: 6, strain: 5, reprisalMult: 5, crit: 0.1,
    scaling: { ins: 'B', fin: 'C' }, req: { ins: 18, fin: 20 }, status: { frost: 18 }, infusable: false, source: { kind: 'keepsake', boss: 'theUnwritten' }, speed: 1.6, region: 3,
    lore: 'A blade with no outline, from a thing with no outline. It cuts the way a missing word cuts a sentence: you do not see the wound, only what is no longer there.',
  },
  // ---------------- Region 4: The Sanctum of the Vigil ----------------
  sanctumSpear: {
    id: 'sanctumSpear', name: 'Sanctum Spear', archetype: 'hybrid', base: 1100, damageType: 'lightning', stamina: 10, strain: 9, reprisalMult: 3, crit: 0.03,
    scaling: { fin: 'C', dev: 'C' }, req: { fin: 22, dev: 20 }, infusable: true, source: { kind: 'shop', cost: 650000, region: 4 }, speed: 1.1, region: 4,
    lore: 'The spear of the Sanctum Knights, blessed to carry the storm. Thunder rides in the haft and gets out through the point. The knights say it sings. They have been awake a long time.',
  },
  vigilMaul: {
    id: 'vigilMaul', name: 'Vigil Maul', archetype: 'heavy', base: 1500, damageType: 'physical', stamina: 22, strain: 22, reprisalMult: 2.4, crit: 0,
    scaling: { mig: 'A' }, req: { mig: 34 }, infusable: true, source: { kind: 'shop', cost: 800000, region: 4 }, speed: 0.58, region: 4,
    lore: 'Made for breaking the silver sentinels when their oaths went wrong. Heavy enough that the swing takes a while, and a sentinel does not move much anyway.',
  },
  lanternBlade: {
    id: 'lanternBlade', name: 'Lantern-Blade', archetype: 'hybrid', base: 1350, damageType: 'lightning', stamina: 11, strain: 10, reprisalMult: 3.2, crit: 0.04,
    scaling: { dev: 'A', fin: 'D' }, req: { dev: 26, fin: 16 }, infusable: false, source: { kind: 'keepsake', boss: 'saintOrvane' }, speed: 1.1, region: 4,
    lore: 'Orvane\'s lantern, reforged with its light inside the steel. It still finds you. Now it finds them.',
  },
  stormTalisman: {
    id: 'stormTalisman', name: 'Storm Talisman', archetype: 'catalyst', base: 400, damageType: 'lightning', stamina: 8, strain: 4, reprisalMult: 2, crit: 0,
    scaling: { dev: 'S' }, req: { dev: 24 }, infusable: false, source: { kind: 'keepsake', boss: 'deaconUnburied' }, speed: 1.0, region: 4,
    lore: 'The Deacon\'s talisman, struck by lightning so many times that the lightning lives in it now. Wielding it channels litanies at half again their power. It hums. It is not a comfortable hum.',
  },
  // ---------------- Region 5: The Deep ----------------
  paleDagger: {
    id: 'paleDagger', name: 'Pale Dagger', archetype: 'fast', base: 3200, damageType: 'physical', stamina: 5, strain: 4, reprisalMult: 5.5, crit: 0.12,
    scaling: { fin: 'A' }, req: { fin: 30 }, status: { bleed: 20 }, infusable: true, source: { kind: 'shop', cost: 9000000, region: 5 }, speed: 1.7, region: 5,
    lore: 'The gaolers\' knife, white as the things they keep. It goes in between things. It is very good at the throat, and at other places where a reprisal finds purchase.',
  },
  nadirGreatsword: {
    id: 'nadirGreatsword', name: 'Nadir Greatsword', archetype: 'heavy', base: 7500, damageType: 'dark', stamina: 20, strain: 19, reprisalMult: 2.6, crit: 0,
    scaling: { mig: 'B', fin: 'B' }, req: { mig: 30, fin: 22 }, infusable: false, source: { kind: 'drop', zone: 'undercroft', tier: 4, chance: 0.04 }, speed: 0.65, region: 5,
    lore: 'A Knight of the Deep\'s sword, black to the hilt and wet. The dark does not dry. Neither does the knight\'s grudge, which came with it.',
  },
  keepersBlackblade: {
    id: 'keepersBlackblade', name: 'Keeper\'s Blackblade', archetype: 'hybrid', base: 6200, damageType: 'dark', stamina: 12, strain: 11, reprisalMult: 3.2, crit: 0.04,
    scaling: { ins: 'B', dev: 'B', mig: 'D' }, req: { ins: 22, dev: 22 }, infusable: false, source: { kind: 'keepsake', boss: 'undercroftKeeper' }, speed: 1.05, region: 5,
    lore: 'The Keeper\'s sword, which stood between the world and what sleeps for an age. It is heavy with the weight of that. It cuts with the dark\'s own edge, and the dark does not care what it cuts.',
  },
  namelessTwinblades: {
    id: 'namelessTwinblades', name: 'Nameless Twinblades', archetype: 'fast', base: 4200, damageType: 'physical', stamina: 7, strain: 6, reprisalMult: 5, crit: 0.1,
    scaling: { fin: 'S' }, req: { fin: 36 }, status: { bleed: 14 }, infusable: false, source: { kind: 'keepsake', boss: 'namelessWanderer' }, speed: 1.8, region: 5,
    lore: 'Two blades, one for each hand, worn to the tang by a revenant who walked further than you have. They are yours now. It walked further. Remember that.',
  },
  // ---------------- Region 6: The Rendering Works ----------------
  renderGreatsword: {
    id: 'renderGreatsword', name: 'Rendering Greatsword', archetype: 'heavy', base: 38000, damageType: 'fire', stamina: 24, strain: 24, reprisalMult: 2.5, crit: 0,
    scaling: { mig: 'S' }, req: { mig: 40 }, infusable: true, source: { kind: 'shop', cost: 160000000, region: 6 }, speed: 0.55, region: 6,
    lore: 'Forged in the First Wick and never cooled. The Rendering Works Knights carry it. It weighs what a door weighs, and it opens things the way a door does not.',
  },
  tallowKatana: {
    id: 'tallowKatana', name: 'Tallow Katana', archetype: 'fast', base: 21000, damageType: 'fire', stamina: 7, strain: 6, reprisalMult: 5, crit: 0.1,
    scaling: { fin: 'A', dev: 'E' }, req: { fin: 34 }, status: { bleed: 16 }, infusable: true, source: { kind: 'drop', zone: 'renderworks', tier: 3, chance: 0.04 }, speed: 1.7, region: 6,
    lore: 'A blade from an eastern land that burned with everything else. The edge is a line of ash that never stops glowing. It draws, cuts, and sheathes in the time it takes an mote to fall.',
  },
  renderersSword: {
    id: 'renderersSword', name: 'Renderer\'s Sword', archetype: 'hybrid', base: 34000, damageType: 'fire', stamina: 13, strain: 13, reprisalMult: 3.4, crit: 0.05,
    scaling: { mig: 'A', fin: 'A', dev: 'C' }, req: { mig: 30, fin: 30, dev: 18 }, infusable: false, source: { kind: 'keepsake', boss: 'theRenderer' }, speed: 1.05, region: 6,
    lore: 'The sword the Lord planted in the Rendering Works floor and leaned on for an age. It is mostly fire now. So was he. Holding it is like holding a decision that was made a very long time ago.',
  },
  firstBlade: {
    id: 'firstBlade', name: 'The First Blade', archetype: 'hybrid', base: 42000, damageType: 'fire', stamina: 12, strain: 14, reprisalMult: 3.6, crit: 0.08,
    scaling: { mig: 'S', fin: 'S' }, req: { mig: 40, fin: 40 }, infusable: false, source: { kind: 'keepsake', boss: 'firstWick' }, speed: 1.1, region: 6,
    lore: 'Not the first blade ever made. The blade the first fire made, when it wanted a shape to be dangerous in. Everything since has been an imitation. Including, arguably, you.',
  },
} satisfies Record<string, WeaponDef>);

WEAPONS.nadirChime = {
  id: 'nadirChime', name: 'Nadir Chime', archetype: 'catalyst', base: 900, damageType: 'dark', stamina: 8, strain: 4, reprisalMult: 2, crit: 0,
  scaling: { ins: 'C', dev: 'C' }, req: { ins: 12, dev: 12 }, infusable: false, source: { kind: 'start' }, speed: 1.0, region: 5,
  lore: 'A bell with no clapper. It rings anyway, when the dark wants it to. Given by the Severing, and it is not clear the Severing expects it back. Wielding it channels hexes.',
};
