import type { ZoneDef } from './types';

export const ZONES: Record<string, ZoneDef> = {
  approach: {
    id: 'approach',
    name: 'The Cindered Approach',
    region: 1,
    materialTier: 1,
    requires: null,
    boss: 'coldPyreWarden',
    secretBoss: 'hangedPilgrim',
    phantom: 'aldric',
    tiers: [
      { name: 'Ash Slopes', enemies: ['hollowPilgrim', 'ashRat'], kills: 6 },
      { name: 'The Toll Gate', enemies: ['tollWarden', 'deserterCrossbow', 'hollowPilgrim'], kills: 8 },
      { name: 'Pyre Yard', enemies: ['pyreHound', 'charredAcolyte'], kills: 10 },
      { name: 'Gallows Walk', enemies: ['gallowsKnight', 'cinderWraith'], kills: 12 },
    ],
    lore: 'A road of packed ash leading up to the Cold Pyre. Once, pilgrims walked it singing. The ash is what is left of the singing.',
  },
  mire: {
    id: 'mire',
    name: 'The Drowned Mire',
    region: 2,
    materialTier: 2,
    requires: 'coldPyreWarden',
    boss: 'mireMother',
    secretBoss: 'choirMaster',
    phantom: 'ghrelt',
    tiers: [
      { name: 'Reed Shallows', enemies: ['bogLeech', 'mireHollow'], kills: 8 },
      { name: 'The Sunken Chapel', enemies: ['drownedChorister', 'mireHollow'], kills: 10 },
      { name: 'Fen of Teeth', enemies: ['fenStalker', 'bogLeech'], kills: 12 },
      { name: 'Rotwood Causeway', enemies: ['rottingKnight', 'rotwoodTreant'], kills: 12 },
      { name: 'The Choir\'s Drowning', enemies: ['drownedChorister', 'rottingKnight', 'fenStalker'], kills: 14 },
    ],
    lore: 'Below the Approach the ash turns to mud and the mud to water, and the water does not drain. Everything that died on the road ended up here eventually, and most of it is still around.',
  },
  archive: {
    id: 'archive',
    name: 'The Archive of Null',
    region: 3,
    materialTier: 2,
    requires: 'mireMother',
    boss: 'archivistNull',
    secretBoss: 'theUnwritten',
    phantom: 'vesna',
    tiers: [
      { name: 'The Threshold Stacks', enemies: ['archiveScribe', 'boundTome'], kills: 10 },
      { name: 'Reading Halls', enemies: ['archiveScribe', 'nullCustodian'], kills: 12 },
      { name: 'The Sealed Wing', enemies: ['boundTome', 'silencedScholar'], kills: 12 },
      { name: 'Crystal Cloister', enemies: ['crystalHollow', 'nullCustodian'], kills: 14 },
      { name: 'Null\'s Vestibule', enemies: ['silencedScholar', 'crystalHollow', 'nullCustodian'], kills: 16 },
    ],
    lore: 'A library built to hold one word so that no one would ever have to read it. The sorcerers who built it read it anyway. The Archive is what they became, shelving themselves.',
  },
  sanctum: {
    id: 'sanctum',
    name: 'The Sanctum of the Vigil',
    region: 4,
    materialTier: 3,
    requires: 'archivistNull',
    boss: 'saintOrvane',
    secretBoss: 'deaconUnburied',
    phantom: 'corvo',
    tiers: [
      { name: 'The Outer Cloister', enemies: ['vigilAcolyte', 'lanternBearer'], kills: 10 },
      { name: 'Hall of Lanterns', enemies: ['lanternBearer', 'sanctumKnight'], kills: 12 },
      { name: 'The Storm Steps', enemies: ['stormGargoyle', 'vigilAcolyte'], kills: 12 },
      { name: 'Chapel of Thunder', enemies: ['deaconOfStorms', 'sanctumKnight'], kills: 14 },
      { name: 'The Silver Gallery', enemies: ['silverSentinel', 'stormGargoyle'], kills: 14 },
      { name: 'The Warden\'s Stair', enemies: ['silverSentinel', 'deaconOfStorms', 'sanctumKnight'], kills: 16 },
    ],
    lore: 'A cathedral on a peak above the clouds, where a single lantern has been kept lit against the coming of the dark. The Vigil was to last one night. It is not clear the night has ended.',
  },
  deep: {
    id: 'deep',
    name: 'The Deep',
    region: 5,
    materialTier: 3,
    requires: 'saintOrvane',
    boss: 'keeperOfTheDeep',
    secretBoss: 'namelessWanderer',
    phantom: 'ysolde',
    tiers: [
      { name: 'The Descent', enemies: ['abyssCrawler', 'deepHollow'], kills: 12 },
      { name: 'Cells of the Pale', enemies: ['paleGaoler', 'deepHollow'], kills: 12 },
      { name: 'The Humanity Well', enemies: ['humanitySprite', 'abyssCrawler'], kills: 14 },
      { name: 'Hall of the Lost', enemies: ['shadowOfTheLost', 'humanitySprite'], kills: 14 },
      { name: 'The Drowned Barracks', enemies: ['deepKnight', 'paleGaoler'], kills: 16 },
      { name: 'The Keeper\'s Threshold', enemies: ['deepKnight', 'shadowOfTheLost', 'paleGaoler'], kills: 18 },
    ],
    lore: 'Under the Sanctum, under the Archive, under the Mire and the road. The place the dark comes from. It is not empty. It has never been empty. That was always the problem.',
  },
  kiln: {
    id: 'kiln',
    name: 'The Kiln of the First Flame',
    region: 6,
    materialTier: 4,
    requires: 'keeperOfTheDeep',
    boss: 'lordOfCinders',
    secretBoss: 'firstEmber',
    tiers: [
      { name: 'The Ashen Field', enemies: ['ashWraith', 'kilnKnight'], kills: 12 },
      { name: 'Drake Roost', enemies: ['emberDrake', 'ashWraith'], kills: 14 },
      { name: 'The Brick Halls', enemies: ['pyreGolem', 'kilnKnight'], kills: 14 },
      { name: 'Shepherds\' Walk', enemies: ['flameShepherd', 'emberDrake'], kills: 16 },
      { name: 'The Lord\'s Antechamber', enemies: ['cinderLordAsh', 'pyreGolem'], kills: 16 },
      { name: 'The Kiln Floor', enemies: ['cinderLordAsh', 'flameShepherd', 'kilnKnight'], kills: 20 },
    ],
    lore: 'Where the First Flame was lit, and where it is kept burning by feeding it everything that comes near. The Lord sits at its heart. He has been sitting there so long that it is hard to say where he ends and the fire begins.',
  },
};

ZONES.abyss = {
  id: 'abyss',
  name: 'The Abyss',
  region: 7,
  materialTier: 4,
  requires: 'lordOfCinders',
  requiresUnlock: 'abyss',
  endless: true,
  boss: 'abyssWatcher',
  tiers: [
    { name: 'The First Dark', enemies: ['abyssCrawler', 'shadowOfTheLost', 'humanitySprite'], kills: 14 },
    { name: 'Where the Road Ends', enemies: ['deepKnight', 'ashWraith'], kills: 16 },
    { name: 'Unlit Halls', enemies: ['paleGaoler', 'cinderLordAsh', 'shadowOfTheLost'], kills: 16 },
    { name: 'The Sleeping Shore', enemies: ['deepKnight', 'pyreGolem', 'humanitySprite'], kills: 18 },
    { name: 'The Watcher\'s Stair', enemies: ['cinderLordAsh', 'deepKnight', 'flameShepherd'], kills: 20 },
  ],
  lore: 'Below the Kiln there is a stair, and the stair does not end. Every landing is a little darker and a little more crowded. Something at the bottom is watching you come down, and it has been counting the steps for longer than there have been steps.',
};

export const ZONE_ORDER: string[] = ['approach', 'mire', 'archive', 'sanctum', 'deep', 'kiln', 'abyss'];
