import { chromium, executablePath } from '../tools/audit/browser.mjs';
const [out, width = '1400', setup = '', wait = '600'] = process.argv.slice(2);
const browser = await chromium.launch({ executablePath });
const page = await browser.newPage({ viewport: { width: Number(width), height: 900 } });
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await page.waitForTimeout(500);
if (setup) await page.evaluate(setup);
await page.waitForTimeout(Number(wait));
await page.screenshot({ path: out });
await browser.close();
console.log('saved', out);
